### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hadeerhma** [mkalewski/sim2net#1]
i installed this simulator and run the _network.py and  get this  error message

**\*  [sim2net] CRITICAL - cannot initialize the simulator:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sim2net/cli/cli.py", line 165, in main
    sim2net = Sim2Net(configuration, vars(args)['application'])
  File "/usr/local/lib/python2.7/dist-packages/sim2net/simulator.py", line 100, in **init**
    self.**get_application_class(application_file)
  File "/usr/local/lib/python2.7/dist-packages/sim2net/simulator.py", line 161, in __get_application_class
    module = __import**(module_name)
  File "./_network.py", line 30
    def __init__(self, node_id, send_message, receive_message):
      ^
IndentationError: expected an indented block

i need  solution

**Comment by mkalewski** [comment]
The above error relates to a file named "./network.py", which is not a part of the "sim2net" simulator.

Apparently, the "./network.py" file (provided as an application/argument to the simulator) has incorrect indentions.

Please, do not report issues that are not caused by or directly related to the "sim2net" simulator.
